apps/user/src/services/enrollment/api.ts
apps/user/src/services/fair/api.ts
apps/user/src/services/faq/api.ts
apps/user/src/services/form/api.ts
apps/user/src/services/notice/api.ts
apps/user/src/services/result/api.ts
apps/user/src/services/user/api.ts

> api 엔드포인트가 변경되어 이를 반영하여 수정했습니다.
<br>
- 각 api별 엔드 포인트 수정
<br>

fix(user): 각 api별 엔드 포인트 수정

---

apps/user/src/components/fair/FairApplicationBox/student/FairStudentApplicationBox.tsx
apps/user/src/components/fair/FairApplicationBox/teacher/FairTeacherApplicationBox.tsx

> 입학 설명회 신청 페이지의 유효성 검사를 추가했습니다.
<br>
- 학생 입학 설명회 신청 페이지 유효성 감사
- 교사 입학 설명회 신청 페이지 유효성 검사
<br>

fix(user): 입학 설명회 유효성 검사

---

apps/admin/src/services/admin/api.ts
apps/admin/src/services/faq/api.ts
apps/admin/src/services/notice/api.ts

> 백엔드의 엔드 포인트가 변경되어 반영했습니다.
<br>
- /question -> /questions
- /notice -> /notices
- /user -> /users
<br>

fix(admin): 변경된 API 반영

---

apps/admin/src/components/common/TableItem/TableItem.tsx
apps/admin/src/components/notice/NoticeTable/NoticeTableItem/NoticeTableItem.tsx

> 공지사항 페이지 리펙토링에서 누락된 기능을 추가했습니다.
<br>
- 공지사항 디테일 라우팅 기능 추가
<br>

feat(admin): 공지사항 페이지 리펙토링 누락된 기능 추가

---

apps/user/src/app/collection/page.tsx
apps/user/src/components/policy/CollectionTable/CollectionTable.tsx
apps/user/src/components/policy/PolicyRoule/PolicyRoule.tsx
apps/user/src/components/policy/index.ts

>  개인정보 수집및 이용에 대한 동의 페이지를 개발했습니다.
<br>
- 페이지 퍼블리싱
- 개인정보 수집 항목 테이블 컴포넌트
<br>

feat(user): 개인정보 수집및 이용에 대한 동의 페이지 개발

---

apps/user/src/app/withdrawal/page.tsx
apps/user/src/app/withdrawal/withdrawal.hook.ts
apps/user/src/components/common/Header/Profile/Profile.hook.ts
apps/user/src/components/common/Header/Profile/Profile.tsx
apps/user/src/components/withdrawal/WithdrawalModal/WithdrawalModal.tsx
apps/user/src/components/withdrawal/index.ts
apps/user/src/constants/common/constants.ts
apps/user/src/hooks/useApiError.ts
apps/user/src/services/auth/api.ts
apps/user/src/services/auth/mutations.ts
apps/user/src/services/user/api.ts
apps/user/src/services/user/mutations.ts
packages/ui/src/Button/Button.style.ts
packages/ui/src/Button/Button.type.ts

> 회원 탈퇴 페이지를 개발했습니다.
<br>
- api 연동
- 회원 탈퇴 페이지 퍼블리싱
<br>

feat(user): 회원 탈퇴 페이지 개발

---

apps/admin/src/utils/functions/formatDate.ts

> toDashedDate 잘못된 리턴값을 수정했습니다.
<br>
-  toDashedDate가 `${year}-${month}-${day}` 형식으로 반환하도록 변경
<br>

fix(admin): toDashedDate 잘못된 리턴값 수정

---

apps/user/src/app/signup/page.tsx
apps/user/src/components/signup/SignUpContent/SignUpContent.hook.ts
apps/user/src/components/signup/SignUpContent/SignUpContent.tsx
apps/user/src/components/signup/Terms/Terms.hook.ts
apps/user/src/components/signup/Terms/Terms.tsx
apps/user/src/components/signup/Terms/TermsItem/TermsItem.tsx
apps/user/src/components/signup/Validate/Validate.tsx
apps/user/src/components/signup/Validate/ValidateItem/ValidateItem.tsx
apps/user/src/components/signup/index.ts
apps/user/src/services/user/api.ts
apps/user/src/services/user/mutations.ts
apps/user/src/stores/index.ts
apps/user/src/stores/user/signup.ts
apps/user/src/types/user/client.ts
apps/user/src/types/user/remote.ts

> 회원가입 페이지를 개발했습니다.
<br>
- 회원가입 페이지 개발
- 컴포넌트 분리
- api 연결
<br>

feat(user): 회원가입 페이지 개발

---

apps/admin/src/app/form/form.hooks.ts
apps/admin/src/app/form/page.tsx
apps/admin/src/components/common/FunctionDropdown/FunctionDropdown.tsx
apps/admin/src/services/form/api.ts

> 검토해야 하는 원서 조회 기능을 추가 했습니다.
<br>
- 검토해야 하는 원서 조회 기능 추가
- 검토해야 하는 원서 상태일 때, 드롭다운 비활성화(삭제)
- 검토해야 하는 원서 상태에서 벗어날 수 있는 토글 버튼 추가
- 만약 정렬 기준을 선택하고 검토해야 하는 원서 상태가 되었을 때, 토글 버튼으로 벗어났다면 본래 정렬 기준을 유지하는 로직 추가
- FunctionDropdown close 기능 추가
<br>

feat(admin): 검토해야 하는 원서 조회 기능 추가

---

apps/user/package.json
apps/user/src/components/form/Contents/ApplicantInformationContent/ApplicantInformationContent.hook.ts
apps/user/src/components/form/Contents/ApplicantInformationContent/ApplicantInformationContent.tsx
apps/user/src/schemas/applicantSchema.ts
apps/user/src/services/form/api.ts
apps/user/src/utils/useDownloadFile.ts
pnpm-lock.yaml

> 지원자 정보의 유효성 검사를 하도록 했습니다.
<br>
- zod를 통해 유효성 검사
- 스키마 생성
<br>
증명사진의 경우에는 지금 refresh가 안되는 문제가 있어서 수정하면서 유효성 검사 로직을 추가할 예정입니다.

feat(user): 지원자 정보 유효성 검사

---

.github/workflows/maru-admin.yml
.github/workflows/maru.yml
apps/admin/src/app/fair/[id]/page.tsx
apps/admin/src/app/faq/[id]/page.tsx
apps/admin/src/app/faq/edit/[id]/page.tsx
apps/admin/src/app/notice/[id]/page.tsx
apps/admin/src/app/notice/edit/[id]/page.tsx
apps/user/next.config.js
apps/user/src/app/fair/page.tsx
apps/user/src/app/fair/student/[id]/page.tsx
apps/user/src/app/fair/teacher/[id]/page.tsx
apps/user/src/app/faq/page.tsx
apps/user/src/app/notice/[id]/page.tsx
apps/user/src/app/notice/page.tsx
apps/user/src/components/faq/FaqList/FaqList.tsx
apps/user/src/components/main/FaqBox/FaqBox.tsx
apps/user/src/components/main/FaqBox/FaqBoxList/FaqBoxList.tsx
apps/user/src/components/main/NoticeBox/NoticeBox.tsx
apps/user/src/components/main/NoticeBox/NoticeBoxList/NoticeBoxList.tsx
apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.tsx
apps/user/src/components/notice/NoticeList/NoticeList.tsx
apps/user/src/services/fair/queries.ts
apps/user/src/services/faq/queries.ts
apps/user/src/services/notice/queries.ts
apps/user/src/types/notice/client.ts

> 마루 PR CI를 구축하고 그 과정에 발생한 에러들을 해결했습니다.
<br>
- 마루(유저) PR CI 구축
- 마루(어드민) PR CI 구축
- 마루(유저) 에러 해결
- 마루(어드민) 에러 해결
<br>

feat(common): 마루 PR CI 구축(Github Actions)

---

apps/user/src/components/form/Contents/EducationContent/EducationContent.hook.ts
apps/user/src/components/form/Contents/EducationContent/EducationContent.tsx
apps/user/src/schemas/EducationSchema.ts

> 출신학교 및 학력 페이지에서 유효성 검사를 해서 조건이 충족되어야지 페이지를 넘어갈 수 있도록 했습니다.
<br>
- 스키마 생성
- 에러 메시지 적용
<br>

feat(user): 출신학교 및 학력 페이지 유효성 검사

---

apps/admin/src/app/registration/page.tsx
apps/admin/src/components/registration/RegistrationTable/RegistrationTable.tsx
apps/admin/src/components/registration/RegistrationTable/RegistrationTableHeader/RegistrationTableHeader.tsx
apps/admin/src/components/registration/RegistrationTable/RegistrationTableItem/RegistrationTableItem.hook.ts
apps/admin/src/components/registration/RegistrationTable/RegistrationTableItem/RegistrationTableItem.tsx
apps/admin/src/constants/common/constant.ts
apps/admin/src/services/registration/api.ts
apps/admin/src/services/registration/queries.ts
apps/admin/src/types/registration/client.ts
apps/admin/src/types/registration/remote.ts

> 입학 등록원의 퍼블리싱과 주요 기능인 파일 미리보기, 다운로드 기능을 개발하였습니다.
<br>
- 파일 미리보기, 다운로드 유틸 함수 개발
<br>

feat(admin): 입학 등록원 개발

---

apps/user/src/app/form/Grade/Score/Score.hook.ts
apps/user/src/app/form/Grade/Score/Score.tsx
apps/user/src/components/form/Contents/EducationContent/EducationContent.hook.ts
apps/user/src/components/form/Contents/EducationContent/EducationContent.tsx
apps/user/src/components/form/Contents/IntroductionContent/IntroductionContent.hook.ts

> 성적 입력 페이지의 유효성 검사를 진행했습니다.
<br>
- hook에서 error를 관리하고 이를 바탕으로 에러가 발생하면 화면을 못바꾸도록 설정했습니다.
<br>

feat(user): 성적 입력 페이지 유효성 검사

---

apps/user/src/components/form/Contents/IntroductionContent/IntroductionContent.hook.ts
apps/user/src/components/form/Contents/IntroductionContent/IntroductionContent.tsx
apps/user/src/schemas/IntroductionSchema.ts

> 자기소개서 페이지에서 유효성 검사를 할 수 있도록 수정했습니다.
<br>
- 스키마 생성
- hook 수정
- isError와 errorMessage에 적용
<br>

fix(user): 자기소개서 페이지 유효성 검사

---

apps/admin/src/app/form/page.tsx
apps/admin/src/components/form/ExportExcelModal/ExportExcelModal.tsx
apps/admin/src/components/form/ExportExcelModal/exportExcelModal.hooks.ts
apps/admin/src/constants/common/constant.ts
apps/admin/src/constants/form/constant.ts
apps/admin/src/services/form/api.ts
apps/admin/src/services/form/queries.ts
apps/admin/src/types/form/client.ts

> 어드민 원서 관리 페이지의 FunctionDropdown 기능 중 - 명단 엑셀로 내보내기 기능을 추가 했습니다.
<br>
- 엑셀로 내보내기 API 연동
- 엑셀로 내보내기 기능 추가
- 엑셀 타입 선택 모달 추가
<br>

feat(admin): 명단 엑셀로 내보내기 기능 추가

---

apps/admin/src/app/form/form.hooks.ts
apps/admin/src/app/form/page.tsx
apps/admin/src/components/form/FormTable/FormTable.tsx
apps/admin/src/components/form/FormTable/FormTableHeader/FormTableHeader.tsx
apps/admin/src/components/form/FormTable/FormTableItem/FormTableItem.tsx
apps/admin/src/services/form/api.ts
apps/admin/src/services/form/mutations.ts
apps/admin/src/store/form/formToPrint.ts
apps/admin/src/store/form/isFormToPrintSelecting.ts
apps/admin/src/types/form/remote.ts
apps/admin/src/utils/functions/isPopupBlocked.ts

> 어드민 원서 관리 페이지의 FunctionDropdown 기능 중 - 원서 출력하기 기능을 추가했습니다.
<br>
- 원서 URL API 연동
- 원서 pdf 새탭으로 열기
- 원서 출력하기 기능 추가
<br>

feat(admin): 원서 출력하기 기능 추가

---

apps/user/src/components/signup/SignUpContent/SignUpContent.tsx

> startTime을 추가하여 인증할때 제한 시간을 5분으로 설정하였습니다.
<br>
- 전송 이후에는 재전송으로 버튼 바뀌도록 수정
- 인증 제한 시간 설정 후 시간이 흐르도록 수정
<br>

fix(user): startTime을 만들어서 인증 제한 시간 설정

---

apps/admin/src/components/form/FormDetail/FormDetail.tsx
apps/admin/src/components/form/FormDetail/ParentInfo/ParentInfo.tsx
apps/admin/src/components/form/FormDetail/formDetail.hooks.ts

> 원서 상세조회의 Navigation 중 보호자 정보를 추가했습니다.
<br>
- 보호자 정보 데이터 동적으로 UI 렌더링
- 보호자 정보 추가
<br>

feat(admin): 원서 상세조회 보호자 정보 추가

---

apps/admin/src/components/form/FormDetail/EducationInfo/EducationInfo.tsx
apps/admin/src/components/form/FormDetail/FormDetail.tsx
apps/admin/src/components/form/FormDetail/formDetail.hooks.ts
apps/admin/src/constants/form/constant.ts
apps/admin/src/types/form/client.ts

> 원서 상세조회의 Navigation 중 출신학교 및 학력을 추가했습니다.
<br>
- 출신학교 및 학력 데이터 동적으로 UI 렌더링
- 출신학교 및 학력 추가
<br>

feat(admin): 원서 상세조회 출신학교 및 학력 추가

---

apps/admin/src/components/form/FormDetail/EducationInfo/EducationInfo.tsx
apps/admin/src/components/form/FormDetail/FormDetail.tsx
apps/admin/src/components/form/FormDetail/Profile/Profile.tsx
apps/admin/src/components/form/FormDetail/TypeInfo/TypeInfo.tsx
apps/admin/src/components/form/FormDetail/formDetail.hooks.ts
apps/admin/src/types/form/client.ts

> 원서 상세조회의 Navigation 중 전형을 추가했습니다.
<br>
- 원서 상세조회 전형 추가
- 각종 반영되지 않은 디자인 반영
- formDetailo.hooks.ts의 data가 undefined일 때 처리
- 원서 상세 step type 추가
<br>

feat(admin): 원서 상세조회 전형 추가

---

apps/user/src/components/Provider.tsx

> Provider에서 토스트가 띄도록 수정했습니다.
<br>
- Provider 수정
<br>

fix(user): 토스트가 뜰 수 있도록 수정

---

apps/user/src/components/form/Contents/ApplicantInformationContent/ApplicantInformationContent.hook.ts
apps/user/src/components/form/Contents/ApplicantInformationContent/ApplicantInformationContent.tsx
apps/user/src/components/form/ProfileUploader/ProfileUploader.hook.ts
apps/user/src/services/form/mutations.ts

> 증명사진 업로드 후 다운로드 url을 재발급해야하는데 이 부분에서 문제가 생겨 해결했습니다.
<br>
- 로컬스토리지에 사진 메타데이터 저장
- 메타데이터를 통한 유효성 검사
<br>

fix(user): 증명사진 업로드 후 다운로드 url 재발급 문제 해결

---

apps/user/src/components/form/Contents/EducationContent/EducationContent.tsx

> import문 문여서 이를 수정했습니다.
<br>
- import 수정
<br>

fix(user): 학교 입력 모달이 뜨도록 수정

---

apps/user/src/apis/authorization/authorization.ts
apps/user/src/services/form/queries.ts
apps/user/src/services/result/queries.ts
apps/user/src/services/user/queries.ts

> 로컬스토리지에서 쿠키로 토큰이 저장되는 위치를 수정했습니다.
<br>
- authorization에서 토큰 가져오는 위치 수정
- 이외에 토큰 가져오는 위치 수정
<br>

fix(user): 토큰 저장소에 맞도록 코드 수정

---

apps/user/src/components/fair/FairApplicationBox/student/FairStudentApplicationBox.tsx
apps/user/src/components/fair/FairApplicationBox/teacher/FairTeacherApplicationBox.tsx
packages/ui/src/Radio/Radio.tsx
packages/ui/src/RadioGroup/RadioGroup.tsx

> 변경된 동의서로 수정하고 라디오에서 라벨을 클릭해도 체크되도록 수정했습니다.
<br>
- 라벨 클릭해도 체크되도록 수정
- 변경된 입학 설명회 동의서로 수정
<br>

fix(user): 변경된 동의서로 수정

---

apps/admin/src/components/form/FormDetail/GradesInfo/Certificate/Certificate.tsx
apps/admin/src/components/form/FormDetail/GradesInfo/GradesInfo.tsx
apps/admin/src/components/form/FormDetail/formDetail.hooks.ts

> 원서 상세조회의 성적 중 자격증을 추가했습니다.
<br>
- 성적 자격증 추가
- 작명 변경 data -> list
<br>

feat(admin): 원서 상세조회 성적 자격증 추가

---

apps/admin/src/components/form/FormDetail/DocumentInfo/DocumentInfo.tsx
apps/admin/src/components/form/FormDetail/FormDetail.tsx
apps/admin/src/components/form/FormDetail/formDetail.hooks.ts

> 원서 상세조회의 Navigation 중 자기소개서를 추가했습니다.
<br>
- 자기소개서 추가
<br>

feat(admin): 원서 상세조회 자기소개서 추가

---

apps/admin/src/components/common/SideBar/SideBar.tsx

> 사이드바 수정 했습니다.
<br>
- 사이드바 수정
<br>

fix(user): 사이드바 수정

---

apps/admin/src/app/Login.hooks.ts
apps/admin/src/app/faq/page.tsx
apps/admin/src/components/faq/FaqDetail/FaqDetail.tsx
apps/admin/src/components/faq/FaqTable/FaqTable.tsx
apps/admin/src/components/faq/FaqTable/FaqTableItem/FaqTableItem.tsx
apps/admin/src/components/notice/NoticeTable/NoticeTableItem/NoticeTableItem.tsx
apps/admin/src/services/faq/api.ts

> 백엔드 연결이 없던 당시의 누락된 기능들을 추가했습니다.
<br>
- 자묻질 잘못된 API 요청 수정
- 자묻질 리스트 검색 기능 추가
- 자묻질 날짜 포맷
- 로그인 시 라우팅 기능 추가
- 자묻질 리스트 아이템 클릭 시 디테일로 이동
<br>

feat(admin): 자묻질 누락된 기능 추가

---

apps/user/src/app/form/FinalSubmissionCompleted/FinalSubmissionCompleted.hook.ts
apps/user/src/app/form/FinalSubmissionCompleted/FinalSubmissionCompleted.tsx

> 원서 최종 제출 완료 페이지의 디자인과 기능이 변경되어 이에 맞게 수정했습니다.
<br>
- hook 수정
- 컴포넌트 수정
<br>

feat(user): 원서 최종 제출 완료 페이지 디자인에 맞게 수정

---

apps/admin/src/components/faq/FaqCreate/FaqCreate.tsx
apps/admin/src/components/faq/FaqEdit/FaqEdit.tsx
apps/admin/src/components/notice/NoticeCreate/NoticeCreate.tsx
apps/admin/src/components/notice/NoticeEdit/NoticeEdit.tsx
apps/admin/src/components/notice/NoticeUploadModal/NoticeUploadModal.tsx

> 어드민 페이지의 디자인 부채 전부 수정했습니다.
<br>
- 디자인 부채 해결
<br>

fix(admin): 버튼 텍스트 수정

---

.idea/material_theme_project_new.xml
.idea/workspace.xml
apps/admin/src/apis/storage/storage.ts
apps/admin/src/services/auth/mutations.ts
pnpm-lock.yaml

> 로그아웃 실패 시에도 쿠키가 삭제되게 했던 로직을 수정했습니다.
<br>
- 로그아웃 실패 시에는 토스트 띄우기
- 로직 수정해서 로컬스토리지도 지우게 만들기
<br>

fix(admin): 쿠키 로그아웃 실패시 삭제 문제 해결

---

apps/admin/package.json
apps/admin/src/services/auth/mutations.ts
pnpm-lock.yaml

> 어드민을 JWT token을 디코딩하여 role을 알아내어 검증하는 로직을 만듭니다.
<br>
- JWT token을 디코딩하여 role을 알아냅니다.
<br>

fix(admin): 어드민 검증 로직 추가

---

apps/user/src/components/fair/FairList/FairItem/FairItem.tsx

> 장소가 길면 ...처리하도록 수정하였습니다.
<br>
-
<br>

style(user): 장소가 길면 ...처리

---

apps/admin/src/app/page.tsx
apps/admin/src/middleware.ts

> 어드민의 middleware를 추가했습니다.
<br>
- middleware 추가
<br>

feat(admin): admin middleware 추가

---

apps/admin/src/components/form/FormDetail/GradesInfo/Grade/GradeItem/GradeItem.tsx

> '미이수'라고 되어있는 부분을 '-'로 바꿨습니다
<br>
- '미이수'->'-'로 바꾸기
<br>

style(admin): 미이수를 디자인에 맞게 -로 바꿈

---

apps/admin/src/components/form/SecondScoreUploadModal/SecondScoreUploadModal.hooks.ts
apps/admin/src/services/form/api.ts
apps/admin/src/services/form/mutations.ts

> 2차 전형점수 엑셀파일을 업로드 할때, 오류가 있는 파일을 다운로드 하고, json응답이 오면 잘못된 파일입니다. 토스트를 띄웁니다
<br>
- 에러에 따른 토스트 띄우기
<br>

feat(admin): 오류난 엑셀파일 다운로드 기능 개발

---

apps/admin/src/app/page.tsx
apps/admin/src/components/common/SideBar/SideBar.tsx
apps/admin/src/components/form/FormDetail/ApplicantInfo/ApplicantInfo.tsx
apps/admin/src/components/form/FormDetail/Profile/Profile.tsx
apps/user/src/app/error.tsx
apps/user/src/app/login/page.tsx
apps/user/src/app/not-found.tsx
apps/user/src/app/signup/page.tsx
apps/user/src/app/withdrawal/page.tsx
apps/user/src/components/common/Footer/Footer.tsx
apps/user/src/components/common/Header/Header.tsx
pnpm-lock.yaml

>next/image태그를 img태그와 lazy로 교체했습니다
<br>
- next/image태그를 교체합니다
<br>

refactor(common): next/image 태그 교체

---

apps/user/src/components/main/GuidelineBox/GuidelineBox.tsx

> 입학전형 요강을 추가했습니다
<br>
- 입학전형 요강 url 추가하기
<br>

feat(user): 입학전형요강 추가

---

apps/user/src/components/notice/NoticeDetailContent/NoticeDetailContent.hook.ts

fix(user): 다운로드할떄 파일 포맷하는 문제 수정

---

apps/admin/src/app/page.tsx

> 어드민 로그인 페이지에 플레이스홀더를 추가했습니다.
<br>
- 어드민 로그인 페이지에 유저 로그인 페이지와 똑같은 플레이스홀더 추가
<br>

fix(admin): 어드민 로그인 페이지 플레이스홀더 추가

---

apps/user/src/components/faq/FaqList/FaqItem/FaqItem.tsx

> faq 페이지에서 faq아이템 내 제목 또는 본문 텍스트가 길어질 경우 아이콘이 작아지는 문제를 해결했습니다.
<br>
- 아이콘이 줄어들지 않도록 IconBox를 씌워 shrink 0 적용
<br>

style(user): faq 텍스트가 길어질 경우 아이콘이 작아지는 문제

---

apps/admin/src/components/common/DataBox/DataBox.tsx
apps/admin/src/components/form/FormDetail/DocumentInfo/DocumentInfo.tsx
apps/admin/src/components/form/FormDetail/FormDetail.tsx

> 디자인과 네비게이션 바와 자기소개서가 다른 문제를 해결합니다.
<br>
- 네비게이션 바 길이 수정
- 네비게이션 바 보더가 다른 문제 해결
- 자기소개서와 학업계획서 길이 수정
- 반응형 적용
<br>
https://github.com/user-attachments/assets/c55398b2-491e-41db-8437-7c62164ffed2

feat(admin): 디자인과 원서상세 페이지가 다른 문제 해결

---

apps/user/src/app/form/FinalSubmission/FinalSubmission.hook.ts
apps/user/src/hooks/useDownloadFile.ts

> 파일 다운로드 및 원서 데이터 불러오기 실패 여부를 확인하고 실패했을 때 toast를 띄웁니다
<br>
- 파일 다운로드 및 원서 데이터 불러오기 실패 여부 확인 후 토스트
<br>

fix(user): 파일 다운로드 및 원서 데이터 불러오기 실패 여부 확인 후 토스트

---

apps/user/src/components/form/FinalFormTable/FinalFormTable.tsx

> 개인정보 수집·이용·제공 동의서문구를 추가합니다
<br>
-개인정보 수집·이용·제공 동의서문구를 추가합니다
<br>

feat(user): 안내 문구 축가

---

apps/user/src/components/form/Contents/ApplicantInformationContent/ApplicantInformationContent.hook.ts
apps/user/src/components/form/Contents/ApplicantInformationContent/ApplicantInformationContent.tsx
apps/user/src/components/form/DraftFormModal/DraftFormModal.tsx
apps/user/src/components/form/FormController/FormController.tsx
apps/user/src/components/form/ProfileUploader/ProfileUploader.tsx
apps/user/src/constants/form/data.ts
apps/user/src/schemas/ApplicantSchema.ts
apps/user/src/types/form/client.ts

> 초안 제출 시 증명사진 업로드 검증 
<br>
- DraftFormModal에서 '확인했습니다' 입력 후 제출 시 증명사진 검증 로직 추가
- 증명사진 미업로드 시 alert로 알림
https://github.com/user-attachments/assets/d03f19be-b5d0-4f5a-8f8e-ce2e6bc03239
<br>

feat(user): 초안 제출 시 증명사진 검증 및 알림

---

apps/admin/src/app/form/page.tsx
apps/admin/src/constants/form/constant.ts
apps/user/src/components/management/StatusBox/StatusBox.config.ts

> 승인을 APPROVED, 접수를 RECEIVED로 수정하였습니다.
<br>
- 승인-APPROVED, 접수-RECEIVED 로 수정
<br>

fix(common): 승인-APPROVED, 접수-RECEIVED 로 수정

---

apps/user/src/app/fair/page.tsx
apps/user/src/app/fair/student/[id]/page.tsx
apps/user/src/app/fair/teacher/[id]/page.tsx
apps/user/src/app/result/final/page.tsx
apps/user/src/app/result/first/page.tsx
apps/user/src/components/enrollment/ExplainBox/ExplainBox.tsx
apps/user/src/components/form/Calculators/AttendanceCalculator/AttendanceCalculator.tsx
apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
apps/user/src/components/main/AdmissionTimelineBox/ApplicationPeriodBox/ApplicationPeriodBox.tsx
apps/user/src/components/main/ScheduleList/ScheduleList.tsx
apps/user/src/utils/formatFormYear.ts
apps/user/src/utils/formatYear.ts
apps/user/src/utils/index.ts

> 입학 요강에 맞춰 출결 상황 및 봉사시간의 마감 기준일을 수정했습니다
<br>
- 날짜 수정
- 입학 요강 확인
<br>

fix(user): 출결 상황 및 봉사시간 마감 기준일 요강에 맞게 수정

---

apps/admin/src/app/form/page.tsx
apps/admin/src/constants/form/constant.ts

> 원서조회 페이지 필터 드롭다운의 제출을 초안제출로 변경하였습니다.
<br>
- 제출을 초안제출로 변경
<br>

style(admin): 어드민 원서조회 페이지 필터 드롭다운 제출->초안제출로 변경

---

apps/admin/src/constants/message/constant.ts
apps/admin/src/services/message/api.ts

> 전체 메세지 발송이 안되는 문제를 수정하였습니다.
<br>
- 원서 승인 RECEIVED를 APPROVED로 수정
- 경로 message를 messages로 수정
<br>

fix(admin): 전체 메세지 발송 안되는 문제 수정

---

apps/admin/src/components/form/FormDetail/FormDetail.tsx
apps/admin/src/components/form/FormDetail/ReceiveStatusChangeModal/ReceiveStatusChangeModal.hook.ts
apps/admin/src/components/form/FormDetail/ReceiveStatusChangeModal/ReceiveStatusChangeModal.tsx
apps/admin/src/components/form/FormDetail/StatusManager/StatusManager.hook.ts
apps/admin/src/components/form/FormDetail/StatusManager/StatusManager.tsx
apps/admin/src/constants/form/constant.ts
apps/admin/src/services/form/api.ts
apps/admin/src/services/form/mutations.ts
apps/admin/src/types/form/client.ts
packages/design-system/src/color.ts

> 원서 상세조회 페이지 내 상태조회, 상태변경 버튼, 서류조회 버튼을 개발했습니다.
<br>
- 원서의 자세한 상태 조회 테이블 추가
- 상태 변경 기능 개발
- 서류조회 기능 개발
<br>

feat(admin): 원서 상세조회시 상태조회, 상태변경, 서류조회 개발

---

apps/user/src/components/common/Footer/Footer.tsx

> 입학담당자 번호를 변경합니다
<br>
- 입학담당자 번호를 변경합니다
<br>

chore(user): 입학담당자 번호 변경

---

apps/admin/src/components/form/FormDetail/GradesInfo/Grade/GradeItem/GradeItem.tsx
apps/admin/src/types/form/client.ts
apps/user/src/components/form/Calculators/GradeCalculator/BasicCalculator/BasicCalculatorItem/BasicCalculatorItem.hook.ts
apps/user/src/components/form/Calculators/GradeCalculator/BasicCalculator/BasicCalculatorItem/BasicCalculatorItem.tsx
apps/user/src/components/form/Calculators/GradeCalculator/BasicCalculator/NewBasicCalculatorItem/NewBasicCalculatorItem.hook.ts
apps/user/src/components/form/Calculators/GradeCalculator/BasicCalculator/NewBasicCalculatorItem/NewBasicCalculatorItem.tsx
apps/user/src/components/form/Calculators/GradeCalculator/GEDCalculator/GEDCalculator.hook.ts
apps/user/src/constants/form/data.ts
apps/user/src/hooks/useGradeCaculation.ts
apps/user/src/types/form/client.ts

> 미이수가 null, 미이수 등 일관적이지 않게 처리되는 부분을 F로 통일하였습니다.
<br>
- 미이수 처리 수정
- 미이수 저장시 F, 조회시 미이수로 조회되는 로직 추가
<br>

fix(common): 미이수 처리가 일관성이지 않은 문제 수정

---

apps/user/src/schemas/EducationSchema.ts

> 학교전화번호를 유효성 검증합니다
<br>
- 유효성 검사
<br>

fix(user): 학교전화번호 유효성 검사

---

apps/user/src/app/form/DraftCompleted/DraftCompleted.hook.ts
apps/user/src/components/form/Contents/EducationContent/EducationContent.tsx
apps/user/src/constants/form/data.ts
apps/user/src/schemas/EducationSchema.ts
apps/user/src/types/form/client.ts

> store와 label이 일치 하지 않고,
FORM.Education store에서는 schoolPhoneNumber가 사용할때는 teacherPhoneNumber로 되어있는 문제를 해결합니다.
<br>
- store수정
- 불일치 수정
<br>

fix(user): store label불일치

---

apps/user/src/app/password/page.tsx
apps/user/src/components/form/Contents/TypeContent/TypeContent.hook.ts
apps/user/src/components/form/Contents/TypeContent/TypeContent.tsx
apps/user/src/hooks/useGradeCaculation.ts

> 고입검정시 사회통합전형 지원가능하도록 변경하였습니다
<br>
- 고입검정 특별전형 계산로직 추가
- 고입검정시 마이스터 인재전형만 블락되도록 변경
<br>

fix(user): 고입검정시 사회통합전형 지원가능하도록 변경
